# Generated by Django 4.1.4 on 2023-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_price',
            field=models.CharField(default='', max_length=100, verbose_name='Stripe Price'),
        ),
    ]
