# Generated by Django 4.1.4 on 2023-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscription_options_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='content_gen_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='content gen limit'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='image_gen_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='image gen limit'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='logo_gen_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='logo gen limit'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='seokeyword_gen_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='seokeyword gen limit'),
        ),
    ]
