# Generated by Django 4.2 on 2024-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_content_gen_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_domain',
            field=models.BooleanField(default=False, verbose_name='Custom Domain'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='free_website_hosting',
            field=models.BooleanField(default=False, verbose_name='free website hosting'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='random_domain',
            field=models.BooleanField(default=False, verbose_name='Random Domain'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='seo_integration',
            field=models.BooleanField(default=False, verbose_name='SEO Integration'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='web_page_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='web page limit'),
        ),
    ]
