# Generated by Django 4.2 on 2024-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscription_custom_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_price',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Stripe Price'),
        ),
    ]
