# Generated by Django 4.2 on 2024-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_subscription_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='classname',
            field=models.CharField(default='', max_length=100, verbose_name='classname'),
        ),
    ]
