# Generated by Django 4.1.4 on 2023-06-23 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(blank=True, choices=[('single', 'Одно значение'), ('multiple', 'Много значений')], default='single', max_length=20, verbose_name='Тип')),
                ('slug', models.CharField(max_length=20, verbose_name='Slug')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Часть',
                'verbose_name_plural': 'Части',
                'ordering': ('-sort', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('template', models.CharField(max_length=100, verbose_name='Шаблон')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('parts', models.ManyToManyField(to='landing.part', verbose_name='Части')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ('-sort', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('company_description', models.TextField(verbose_name='Описание компании')),
                ('hero_list', models.TextField(default='', verbose_name='Список Hero')),
                ('hero_long_list', models.TextField(default='', verbose_name='Список Hero long')),
                ('services_list', models.TextField(default='', verbose_name='Список Services')),
                ('about_us_list', models.TextField(default='', verbose_name='Список About us')),
                ('statistics_list', models.TextField(default='', verbose_name='Список Statistics')),
                ('testimonials_list', models.TextField(default='', verbose_name='Список Testimonials')),
                ('cta_list', models.TextField(default='', verbose_name='Список CTA')),
                ('cta_long_list', models.TextField(default='', verbose_name='Список CTA long')),
                ('hero', models.CharField(max_length=100, verbose_name='Hero')),
                ('hero_long', models.TextField(verbose_name='Hero long')),
                ('services', models.TextField(verbose_name='Services')),
                ('about_us', models.TextField(default='', verbose_name='About us')),
                ('statistics', models.TextField(verbose_name='Statistics')),
                ('testimonials', models.TextField(verbose_name='Testimonials')),
                ('cta', models.CharField(max_length=100, verbose_name='CTA')),
                ('cta_long', models.TextField(verbose_name='CTA long')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Лэндинг',
                'verbose_name_plural': 'Лэндинги',
            },
        ),
    ]
