# Generated by Django 4.1.4 on 2023-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='landing',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='landing',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='landing',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Youtube'),
        ),
    ]
