# Generated by Django 4.1.4 on 2023-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_part_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='landing',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='landing',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон'),
        ),
    ]
