# Generated by Django 4.1.4 on 2023-07-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_landing_address_landing_email_landing_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Домен по умолчанию'),
        ),
    ]
