# Generated by Django 4.1.4 on 2023-07-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_landing_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='example',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='example_templates', to='landing.landing', verbose_name='Пример'),
        ),
    ]
