# Generated by Django 4.1.4 on 2023-08-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_template_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='text_only',
            field=models.BooleanField(default=True, verbose_name='Text Only'),
        ),
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Landing')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Midjourney Message Id')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.landing')),
            ],
        ),
    ]
