# Generated by Django 4.1.4 on 2023-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_landing_text_only_landingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimage',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image type'),
        ),
    ]
