# Generated by Django 4.1.4 on 2023-08-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_landingimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Image description'),
        ),
    ]
