# Generated by Django 4.1.4 on 2023-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_landingimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='product_features_list',
            field=models.TextField(default='', verbose_name='Product Features List'),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_price',
            field=models.CharField(default='20 $', max_length=255, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_title',
            field=models.CharField(default='Product', max_length=255, verbose_name='Product Title'),
        ),
    ]
