# Generated by Django 4.1.4 on 2023-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_landing_product_features_list_landing_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='product_price',
            new_name='product_price_list',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='product_title',
            new_name='product_title_list',
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_features_list',
            field=models.TextField(default='Feature #1|Feature #2|Feature #3|Feature #4', verbose_name='Product Features List'),
        ),
    ]
