# Generated by Django 4.1.4 on 2023-08-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_rename_product_price_landing_product_price_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='product_features_list',
            new_name='product_features',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='product_price_list',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='product_title_list',
            new_name='product_title',
        ),
    ]
