# Generated by Django 4.1.4 on 2023-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_rename_product_features_list_landing_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='product_features_list',
            field=models.TextField(default='Feature #1|Feature #2|Feature #3|Feature #4', verbose_name='Product Features List'),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_price_list',
            field=models.CharField(default='20 $', max_length=255, verbose_name='Product Price List'),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_title_list',
            field=models.CharField(default='Product', max_length=255, verbose_name='Product Title List'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_features',
            field=models.TextField(default='Feature #1|Feature #2|Feature #3|Feature #4', verbose_name='Product Features'),
        ),
    ]
