# Generated by Django 4.1.4 on 2023-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_landing_product_features_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='cta',
            field=models.CharField(max_length=500, verbose_name='CTA'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='hero',
            field=models.CharField(max_length=500, verbose_name='Hero'),
        ),
    ]
