# Generated by Django 4.1.4 on 2023-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_alter_landing_cta_alter_landing_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='company_name',
            field=models.CharField(default="{'id': '', 'text': ''}", max_length=100, verbose_name='Название компании'),
        ),
    ]
