# Generated by Django 4.1.4 on 2023-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_landing_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='facebook',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='instagram',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='twitter',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=255, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='youtube',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=255, verbose_name='Youtube'),
        ),
    ]
