# Generated by Django 4.1.4 on 2023-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_alter_landing_facebook_alter_landing_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='address',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='email',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='phone',
            field=models.CharField(blank=True, default="{'id': '', 'text': ''}", max_length=100, verbose_name='Телефон'),
        ),
    ]
