# Generated by Django 4.1.4 on 2023-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_alter_landing_address_alter_landing_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='address',
            field=models.CharField(blank=True, default="{'id': 'ad', 'text': ''}", max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='email',
            field=models.CharField(blank=True, default="{'id': 'em', 'text': ''}", max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='facebook',
            field=models.CharField(blank=True, default="{'id': 'fc', 'text': ''}", max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='instagram',
            field=models.CharField(blank=True, default="{'id': 'in', 'text': ''}", max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='phone',
            field=models.CharField(blank=True, default="{'id': 'ph', 'text': ''}", max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='twitter',
            field=models.CharField(blank=True, default="{'id': 'tw', 'text': ''}", max_length=255, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='youtube',
            field=models.CharField(blank=True, default="{'id': 'yt', 'text': ''}", max_length=255, verbose_name='Youtube'),
        ),
    ]
