# Generated by Django 4.1.4 on 2023-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_alter_landing_address_alter_landing_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='address',
            field=models.CharField(blank=True, default="{'id': 'ad', 'text': 'Enter Your Address'}", max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='email',
            field=models.CharField(blank=True, default="{'id': 'em', 'text': 'Enter Your Email'}", max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='phone',
            field=models.CharField(blank=True, default="{'id': 'ph', 'text': 'Enter Your Phone Number'}", max_length=100, verbose_name='Телефон'),
        ),
    ]
