# Generated by Django 4.1.4 on 2023-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_landing_address_alter_landing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='basic',
            field=models.IntegerField(blank=True, default=0, verbose_name='basic Limit'),
        ),
        migrations.AddField(
            model_name='template',
            name='free',
            field=models.IntegerField(blank=True, default=0, verbose_name='Free Limit'),
        ),
        migrations.AddField(
            model_name='template',
            name='pro',
            field=models.IntegerField(blank=True, default=0, verbose_name='pro Limit'),
        ),
        migrations.AddField(
            model_name='template',
            name='starter',
            field=models.IntegerField(blank=True, default=0, verbose_name='starter Limit'),
        ),
    ]
