# Generated by Django 4.1.4 on 2024-01-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_template_basic_template_free_template_pro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='product_features',
            field=models.TextField(default="[{'id': 'pfl1', 'text': 'Feature 1'}, {'id': 'pfl2', 'text': 'Feature 2'}, {'id': 'pfl3', 'text': 'Feature 3'}, {'id': 'pfl4', 'text': 'Feature 4'}]", verbose_name='Product Features'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_features_list',
            field=models.TextField(default="[{'id': 'pfl1', 'text': 'Feature 1'}, {'id': 'pfl2', 'text': 'Feature 2'}, {'id': 'pfl3', 'text': 'Feature 3'}, {'id': 'pfl4', 'text': 'Feature 4'},{'id': 'pfl5', 'text': 'Feature 5'}]", verbose_name='Product Features List'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_price',
            field=models.CharField(default="{'id': 'ppl1', 'text': '10$'}", max_length=255, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_price_list',
            field=models.CharField(default="[{'id': 'ppl1', 'text': '10$'}, {'id': 'ppl2', 'text': '20$'}, {'id': 'ppl3', 'text': '30$'}, {'id': 'ppl4', 'text': '40$'}, {'id': 'ppl5', 'text': '50$'}]", max_length=255, verbose_name='Product Price List'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_title',
            field=models.CharField(default="{'id': 'ptl2', 'text': 'product 2'}", max_length=255, verbose_name='Product Title'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='product_title_list',
            field=models.CharField(default="[{'id': 'ptl1', 'text': 'Product 1'}, {'id': 'ptl2', 'text': 'product 2'}, {'id': 'ptl3', 'text': 'product 3'}, {'id': 'ptl4', 'text': 'product 4'}, {'id': 'ptl5', 'text': 'product 5'}]", max_length=255, verbose_name='Product Title List'),
        ),
    ]
