# Generated by Django 4.1.4 on 2024-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_alter_landing_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='light',
            field=models.IntegerField(blank=True, default=0, verbose_name='Light Limit'),
        ),
        migrations.AlterField(
            model_name='template',
            name='basic',
            field=models.IntegerField(blank=True, default=0, verbose_name='Basic Limit'),
        ),
        migrations.AlterField(
            model_name='template',
            name='pro',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pro Limit'),
        ),
        migrations.AlterField(
            model_name='template',
            name='starter',
            field=models.IntegerField(blank=True, default=0, verbose_name='Starter Limit'),
        ),
    ]
