# Generated by Django 4.1.4 on 2024-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_template_light_alter_template_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='product_link',
            field=models.TextField(default="{'id': 'prl', 'text': 'Your link'}", verbose_name='Product Redirect Link'),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_link_list',
            field=models.TextField(default="[{'id': 'prl', 'text': 'Your link'}]", verbose_name='Product Redirect Link List'),
        ),
    ]
