# Generated by Django 4.1.4 on 2024-01-24 05:47

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_landing_product_link_landing_product_link_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='active_elements',
            field=models.JSONField(blank=True, default=landing.models.Landing.default_active_elements),
        ),
    ]
