# Generated by Django 4.1.4 on 2024-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_landing_active_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='PrimaryFont',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('Helvetica, sans-serif', 'Helvetica'), ('Arial, sans-serif', 'Arial'), ('Arial Black, sans-serif', 'Arial Black'), ('Verdana, sans-serif', 'Verdana'), ('Tahoma, sans-serif', 'Tahoma'), ('Trebuchet MS, sans-serif', 'Trebuchet MS'), ('Impact, sans-serif', 'Impact'), ('Gill Sans, sans-serif', 'Gill Sans'), ('Times New Roman, serif', 'Times New Roman'), ('Georgia, serif', 'Georgia'), ('Palatino, serif', 'Palatino'), ('Baskerville, serif', 'Baskerville'), ('Andalé Mono, monospace', 'Andalé Mono'), ('Courier, monospace', 'Courier'), ('Lucida, monospace', 'Lucida'), ('Monaco, monospace', 'Monaco'), ('Bradley Hand, cursive', 'Bradley Hand'), ('Brush Script MT, cursive', 'Brush Script MT'), ('Luminari, fantasy', 'Luminari'), ('Comic Sans MS, cursive', 'Comic Sans MS')], default='default', max_length=27, verbose_name='Primary Font'),
        ),
        migrations.AddField(
            model_name='landing',
            name='SecondaryFont',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('Helvetica, sans-serif', 'Helvetica'), ('Arial, sans-serif', 'Arial'), ('Arial Black, sans-serif', 'Arial Black'), ('Verdana, sans-serif', 'Verdana'), ('Tahoma, sans-serif', 'Tahoma'), ('Trebuchet MS, sans-serif', 'Trebuchet MS'), ('Impact, sans-serif', 'Impact'), ('Gill Sans, sans-serif', 'Gill Sans'), ('Times New Roman, serif', 'Times New Roman'), ('Georgia, serif', 'Georgia'), ('Palatino, serif', 'Palatino'), ('Baskerville, serif', 'Baskerville'), ('Andalé Mono, monospace', 'Andalé Mono'), ('Courier, monospace', 'Courier'), ('Lucida, monospace', 'Lucida'), ('Monaco, monospace', 'Monaco'), ('Bradley Hand, cursive', 'Bradley Hand'), ('Brush Script MT, cursive', 'Brush Script MT'), ('Luminari, fantasy', 'Luminari'), ('Comic Sans MS, cursive', 'Comic Sans MS')], default='default', max_length=27, verbose_name='Secondary Font'),
        ),
    ]
