# Generated by Django 4.1.4 on 2024-01-29 13:15

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_landing_primaryfont_landing_secondaryfont'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='about_us_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='cta_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='hero_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='hero_long_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='product_title_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='services_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='statistics_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
        migrations.AddField(
            model_name='landing',
            name='testimonials_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
    ]
