# Generated by Django 4.1.4 on 2024-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_landing_about_us_colors_landing_cta_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='map',
            field=models.CharField(blank=True, default="{'id': 'map', 'text': ''}", max_length=1055, verbose_name='Map'),
        ),
        migrations.AddField(
            model_name='landingimage',
            name='alt',
            field=models.TextField(blank=True, null=True, verbose_name='Image Alt Text'),
        ),
    ]
