# Generated by Django 4.1.4 on 2024-01-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_landing_map_landingimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
