# Generated by Django 4.1.4 on 2024-02-01 12:01

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_landing_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='desc_colors',
            field=models.JSONField(blank=True, default=landing.models.Landing.hero_colors_dict),
        ),
    ]
