# Generated by Django 4.2 on 2024-03-15 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0030_landing_desc_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sections', models.CharField(default='', max_length=100, verbose_name='Sections')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='Description')),
                ('language', models.CharField(default='', max_length=100, verbose_name='language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
