# Generated by Django 4.2 on 2024-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='sectionHeadings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
