# Generated by Django 4.2 on 2024-03-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_pages_sectionheadings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='imageStyle',
            field=models.CharField(default='', max_length=300, verbose_name='Image Style'),
        ),
        migrations.AddField(
            model_name='pages',
            name='imageType',
            field=models.CharField(default='', max_length=300, verbose_name='Image type'),
        ),
        migrations.AddField(
            model_name='pages',
            name='textAmt',
            field=models.CharField(default='', max_length=300, verbose_name='Text amt'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='language',
            field=models.CharField(default='', max_length=300, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='sections',
            field=models.CharField(default='', max_length=300, verbose_name='Sections'),
        ),
    ]
