# Generated by Django 4.2 on 2024-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_pages_imagestyle_pages_imagetype_pages_textamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='themeId',
            field=models.CharField(default='', max_length=300, verbose_name='themeId'),
        ),
    ]
