# Generated by Django 4.2 on 2024-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_pages_themeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='themeId',
            field=models.CharField(default='-1', max_length=300, verbose_name='themeId'),
        ),
    ]
