# Generated by Django 4.2 on 2024-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_alter_pages_themeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='allPageData',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
