# Generated by Django 4.2 on 2024-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_pages_allpagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='isFirst',
            field=models.CharField(default='false', max_length=300, verbose_name='isFirst'),
        ),
    ]
