# Generated by Django 4.2 on 2024-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_pages_isfirst'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='randomStr',
            field=models.CharField(default='', max_length=300, verbose_name='random string'),
        ),
    ]
