# Generated by Django 4.2 on 2024-04-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0038_pages_randomstr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='randomStr',
            new_name='randomString',
        ),
    ]
