# Generated by Django 4.2 on 2024-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0039_rename_randomstr_pages_randomstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='favicon',
            field=models.CharField(default='false', max_length=300, verbose_name='favicon'),
        ),
    ]
