# Generated by Django 4.2 on 2024-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_pages_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='metaDescription',
            field=models.CharField(default='false', max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pages',
            name='metaKeywords',
            field=models.CharField(default='false', max_length=300, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pages',
            name='metaTitle',
            field=models.CharField(default='false', max_length=300, verbose_name='Meta Title'),
        ),
    ]
