# Generated by Django 4.2 on 2024-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_pages_metadescription_pages_metakeywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='favicon',
            field=models.CharField(default='', max_length=300, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='metaDescription',
            field=models.CharField(default='', max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='metaKeywords',
            field=models.CharField(default='', max_length=300, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='metaTitle',
            field=models.CharField(default='', max_length=300, verbose_name='Meta Title'),
        ),
    ]
