# Generated by Django 4.2 on 2024-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_alter_pages_favicon_alter_pages_metadescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='domain',
            field=models.CharField(default='', max_length=300, verbose_name='Domain'),
        ),
    ]
