# Generated by Django 4.2 on 2024-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_pages_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='customDomain',
            field=models.CharField(default='', max_length=300, verbose_name='Custom domain'),
        ),
    ]
