# Generated by Django 4.2 on 2024-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='keywords',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
