# Generated by Django 4.2 on 2024-02-28 06:09

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='thumbnail',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
