"""
Django settings for landing_ai project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


LOGIN_URL = 'login'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-iXXXX'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

X_FRAME_OPTIONS = 'ALLOWALL'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'base',
    'account',
    'user',
    'payments',
    'landing',


    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',

    'modelcluster',
    'taggit',
    'blog'

]

MIDDLEWARE = [
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "base.middleware.CustomMiddleware"

]



ROOT_URLCONF = 'landing_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES[0]['OPTIONS']['context_processors'].append("base.context_processors.context_controller")

WSGI_APPLICATION = 'landing_ai.wsgi.application'

AUTH_USER_MODEL = 'user.User'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'landly_ai',
        'USER': 'postgres',
        # 'PASSWORD': '123456789',
        'HOST': 'PostgreSQL-17',
        'PORT': '5432',
    }
}

# Server [localhost]:
# Database [postgres]:
# Port [5433]:
# Username [postgres]:

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'


# Define the STATIC_URL, which specifies the URL prefix for serving static files.

# Define STATICFILES_DIRS to specify additional directories for static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Add your additional directories here
]

# Define STATIC_ROOT as a single directory where Django will collect static files during the "collectstatic" command.
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')  # Replace with your desired path


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CHAT_GPT_KEY = 'TOKEN'


# CHAT_GPT_KEY = 'null'
NEW_CHAT_GPT_KEY = 'TOKEN'



# Test
STRIPE_PUBLISHABLE_KEY = 'TOKEN'
STRIPE_SECRET_KEY = 'TOKEN'
STRIPE_ENDPOINT_SECRET = 'TOKEN'

MIDJOURNEY_API_KEY = 'TOKEN'

# EMAIL_FROM = 'info@landlyai.com'
# EMAIL_HOST = 'mail.adm.tools'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'info@landlyai.com'
# EMAIL_HOST_PASSWORD = 'Js76XHvf68'
DOMAIN_URL = 'http://127.0.0.1:8000/'

WAGTAIL_SITE_NAME = 'landly'

WAGTAILADMIN_BASE_URL = 'localhost:80/cms'

GMAIL_EMAIL_ADDRESS = 'info@landlyai.com'
GMAIL_EMAIL_PASSWORD = 'TOKEN'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'info@landlyai.com'
EMAIL_HOST_PASSWORD = 'TOKEN'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
