# Generated by Django 4.1.4 on 2023-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Почта'), ('address', 'Адрес')], default='phone', max_length=12, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакт',
                'ordering': ('-sort', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('-sort', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, default='', verbose_name='Email обратной связи (через ;)')),
                ('main_title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('main_text', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.TextField(blank=True, verbose_name='Текст кнопки')),
                ('video', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео (YouTube)')),
                ('youtube', models.CharField(blank=True, default='', max_length=255, verbose_name='Youtube')),
                ('twitter', models.CharField(blank=True, default='', max_length=255, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Текст в футере')),
                ('copyright', models.CharField(blank=True, default='', max_length=100, verbose_name='Copyright')),
                ('about_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('about_sub_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Подзаголовок')),
                ('about_text', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('pricing_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('pricing_sub_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
