# Generated by Django 4.1.4 on 2023-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_sub_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Подзаголовок о нас'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_text',
            field=models.TextField(blank=True, default='', verbose_name='Описание о нас'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок о нас'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='pricing_sub_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Подзаголовок подписок'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='pricing_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок подписок'),
        ),
    ]
