# Generated by Django 4.1.4 on 2023-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='statistics_text',
            field=models.TextField(blank=True, default='', verbose_name='Статистика'),
        ),
    ]
