# Generated by Django 4.1.4 on 2023-11-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_setting_statistics_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Subscriber List',
                'verbose_name_plural': 'Subscriber List',
            },
        ),
    ]
